# -*- coding: utf-8 -*-
"""data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/199quJPc8lGd0bd8f1gQITepfAdOZnEdN
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install sodapy

import numpy as np
import pandas as pd
from sodapy import Socrata

"""**Leyendo los datos 'Casos positivos de COVID-19 en Colombia'**"""

socrata_domain = "www.datos.gov.co"
socrata_dataset_identifier = "gt2j-8ykr"

client = Socrata(socrata_domain, None)
results = client.get(socrata_dataset_identifier,limit=1000000000)
df = pd.DataFrame.from_dict(results)
df.shape

df.columns

df.head(5)