# -*- coding: utf-8 -*-
"""exploracióndatos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DYyqsGg53U6jRDuKMDwNMjNl-hryt3S0
"""

pip install leila

import numpy as np
import pandas as pd
import leila

from leila import datos_gov

# Abrir la base de datos original con los metadatos (asset inventory)
# del Portal de Datos Abiertos
inventario = datos_gov.tabla_inventario()

columnas_valor = {"nombre": ["COVID"], "tipo": ["conjunto de datos"], "dueno": ["Instituto Nacional de Salud"]}
# Buscar bases cuya descripción incluya
#columnas_valor = {"descripcion": ["economia", "ambiente"]}
tabla_filtrada = datos_gov.filtrar_tabla(columnas_valor)
tabla_filtrada

tabla_id = tabla_filtrada.iloc[0].numero_api
datos1 = datos_gov.cargar_base(tabla_id)
datos1.head()

tabla_id = tabla_filtrada.iloc[1].numero_api
datos2 = datos_gov.cargar_base(tabla_id)
datos2.head()

tabla_id = tabla_filtrada.iloc[2].numero_api
datos3 = datos_gov.cargar_base(tabla_id)
datos3.head()

columnas_valor2 = {"nombre": ["tabaco"], "tipo": ["conjunto de datos"]}
tabla_filtrada2 = datos_gov.filtrar_tabla(columnas_valor2)
tabla_filtrada2

datost= datos_gov.cargar_base('6sem-aayu')
datost.head()

# Se importan las funciones de la librería
from leila import reporte

# Se invoca la función para generar el reporte de calidad de datos
reporte.generar_reporte(df=datos3)

datos3[['atenci_n', 'estado']].groupby(['atenci_n', 'estado']).size()

datos3[['estado','atenci_n']].groupby(['estado','atenci_n']).size()