# -*- coding: utf-8 -*-
"""exploracióndatos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DYyqsGg53U6jRDuKMDwNMjNl-hryt3S0

# Exploración datos COVID
"""

pip install leila

import numpy as np
import pandas as pd
import leila

"""## Bases de datos existentes en datos gov"""

from leila import datos_gov

# Abrir la base de datos original con los metadatos (asset inventory) del Portal de Datos Abiertos
inventario = datos_gov.tabla_inventario()

# Búsqueda
columnas_valor = {"nombre": ["COVID"], "tipo": ["conjunto de datos"], "dueno": ["Instituto Nacional de Salud"]}

tabla_filtrada = datos_gov.filtrar_tabla(columnas_valor)
tabla_filtrada

"""### Primera base de datos"""

tabla_id = tabla_filtrada.iloc[0].numero_api
datos1 = datos_gov.cargar_base(tabla_id)
datos1.head()

"""### Segunda base de datos"""

tabla_id = tabla_filtrada.iloc[1].numero_api
datos2 = datos_gov.cargar_base(tabla_id)
datos2.head()

"""### Tercer base de datos"""

tabla_id = tabla_filtrada.iloc[2].numero_api
datos3 = datos_gov.cargar_base(tabla_id)
datos3.head()

"""### Reporte HTML de la tercer base de datos"""

from leila import reporte
reporte.generar_reporte(df=datos3)

"""Según el reporte hay correlación entre atención y estado por lo que se desea ver cómo estan calsificadas. Es necesaro analizar los na"""

datos3[['atenci_n', 'estado']].groupby(['atenci_n', 'estado']).size()

datos3[['estado','atenci_n']].groupby(['estado','atenci_n']).size()

"""# Exploración de datos TABACO"""

columnas_valor2 = {"nombre": ["tabaco"], "tipo": ["conjunto de datos"]}
tabla_filtrada2 = datos_gov.filtrar_tabla(columnas_valor2)
tabla_filtrada2

datost= datos_gov.cargar_base('6sem-aayu')
datost.head()

"""# Exploración de datos CALIDAD DEL AIRE"""

from leila import datos_gov
columnas_valor3 = {"nombre": ["calidad del aire"], "tipo": ["conjunto de datos"]}
tabla_filtrada3 = datos_gov.filtrar_tabla(columnas_valor3)

tabla_filtrada3=tabla_filtrada3.sort_values('fecha_actualizacion', ascending=False)
tabla_filtrada3